import uuid
from django.db import models
from common.models import ActiveStatusMixin


# Create your models here.
class Equipment(ActiveStatusMixin, models.Model):

    class EquipmentType(models.TextChoices):
        CAMERA = 'camera', 'Camera'
        LENS = 'lens', 'Lens'
        DRONE = 'drone', 'Drone'
        LIGHTING = 'lighting', 'Lighting'
        OTHER = 'other', 'Other'

    brand = models.CharField(
        max_length=100,
    )

    model = models.CharField(
        max_length=100,
    )

    equipment_type = models.CharField(
        max_length=50,
        choices=EquipmentType,
        default=EquipmentType.OTHER,
    )

    cover_image = models.ImageField(
        upload_to='equipment_covers/',
        blank=True,
        null=True,
        verbose_name='Equipment Image',
    )

    specifications = models.TextField(
        blank=True,
    )

    internal_id = models.CharField(
        max_length=50,
        unique=True,
        help_text='Internal inventory ID (generated by the studio).',
    )

    purchase_date = models.DateField(
        blank=True,
        null=True,
    )

    notes = models.TextField(
        blank=True,
    )


    class Meta:
        ordering = ['brand', 'model', 'internal_id']
        verbose_name_plural = 'Equipment'

    def __str__(self):
        return f'{self.brand} {self.model} ({self.get_equipment_type_display()})'

    def clean(self):
        super().clean()
        if self.internal_id is not None:
            self.internal_id = self.internal_id.strip()

    def save(self, *args, **kwargs):
        self.internal_id = (self.internal_id or '').strip()

        if not self.internal_id:
            self.internal_id = f'INV-{uuid.uuid4().hex[:8].upper()}'

        super().save(*args, **kwargs)