# Generated by Django 6.0.3 on 2026-03-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_groups'),
        ('bookings', '0006_bookingrequest_user_alter_bookingrequest_city_and_more'),
        ('inventory', '0004_equipment_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_equipment',
            field=models.ManyToManyField(blank=True, related_name='favorite_by', to='inventory.equipment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_packages',
            field=models.ManyToManyField(blank=True, related_name='favorite_by', to='bookings.servicepackage'),
        ),
    ]
