# Generated by Django 6.0.1 on 2026-01-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this item without deleting it')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(choices=[('camera', 'Camera'), ('lens', 'Lens'), ('drone', 'Drone'), ('lighting', 'Lighting'), ('other', 'Other')], default='other', max_length=50)),
                ('specifications', models.TextField(blank=True)),
                ('internal_id', models.CharField(help_text='Internal inventory ID (generated by the studio).', max_length=50, unique=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('productions', models.ManyToManyField(blank=True, related_name='equipment', to='productions.production')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['brand', 'model', 'internal_id'],
            },
        ),
    ]
