# Generated by Django 6.0.3 on 2026-03-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_seed_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_covers/', verbose_name='Equipment Image'),
        ),
    ]
