# Generated by Django 6.0.1 on 2026-01-30 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='category_covers/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('title', models.CharField(max_length=150)),
                ('date_created', models.DateField()),
                ('location', models.CharField(blank=True, max_length=150)),
                ('short_description', models.CharField(blank=True, help_text='Short teaser used in listings and cards.', max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='production_covers/')),
                ('video_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='productions.category')),
            ],
            options={
                'ordering': ['-date_created', '-created_at'],
            },
        ),
    ]
