# Generated by Django 6.0.2 on 2026-02-20 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
