# Generated by Django 6.0.2 on 2026-02-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_equipment_productions'),
        ('productions', '0002_alter_production_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='productions', to='inventory.equipment'),
        ),
    ]
