# Generated by Django 6.0.1 on 2026-01-30 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this item without deleting it')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_hours', models.PositiveIntegerField(default=8, help_text='Typical coverage duration in hours.')),
                ('max_photos_included', models.PositiveIntegerField(default=200, help_text='Approximate number of edited photos included.')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('event_date', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('heard_from', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google search'), ('friend', 'Friend referral'), ('other', 'Other')], default='other', help_text='Where did you hear about us?', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes visible only in the admin area.')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.servicepackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
