# Generated by Django 6.0.2 on 2026-02-21 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_bookingrequest_full_name_and_more'),
        ('productions', '0002_alter_production_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='productions.category'),
        ),
    ]
