# Generated by Django 6.0.3 on 2026-03-30 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_seed_booking_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='city',
            field=models.CharField(blank=True, help_text='City for contact purposes', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number for contact purposes', max_length=30, null=True),
        ),
    ]
